# Generated by Django 4.2.5 on 2023-10-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_chunk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
