# Generated by Django 4.2.5 on 2023-10-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
