# Generated by Django 4.2.5 on 2023-10-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_chunk_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='url',
            new_name='file',
        ),
    ]
