# Generated by Django 4.2.5 on 2023-10-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_rename_url_uploadedfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='chunk_url',
            new_name='chunk_file',
        ),
    ]
