# Generated by Django 4.2.5 on 2023-10-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_rename_chunk_url_chunk_chunk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
